Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans->
* Their are no dimensions in list but array has. 

* Arrays need to be declared. Lists don't, since they are built into Python. Lists are created by simply enclosing a sequence of elements into square brackets. Creating an array, on the other hand, requires a specific function from either the array module (i.e., array.array()) or NumPy package (i.e., numpy.array()). Because of this, lists are used more often than arrays.

* Arrays can store data very compactly and are more efficient for storing large amounts of data.

* Arrays are great for numerical operations; lists cannot directly handle math operations. For example, you can divide each element of an array by the same number with just one line of code. If you try the same with a list, you'll get an error.


In [16]:
import numpy as np
list_ = ['1','2','3','4','5' ]
array_list = np.array(object = list_)
print(type(list_))
type(array_list)

<class 'list'>


numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

Ans-> 

In [17]:
def d_type(l):
    for i in l:
        print(type(i),"->",i)
d_type(list_)
d_type(array_list)

<class 'str'> -> 1
<class 'str'> -> 2
<class 'str'> -> 3
<class 'str'> -> 4
<class 'str'> -> 5
<class 'numpy.str_'> -> 1
<class 'numpy.str_'> -> 2
<class 'numpy.str_'> -> 3
<class 'numpy.str_'> -> 4
<class 'numpy.str_'> -> 5


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Ans-> 

In [18]:
array_list = np.array(object = list_, dtype = int)
array_list

array([1, 2, 3, 4, 5])

Yes, their is difference between the data types of the elements present in both the vaeiables.

In [19]:
def d_type(l):
    for i in l:
        print(type(i),"->",i)
d_type(list_)
d_type(array_list)

<class 'str'> -> 1
<class 'str'> -> 2
<class 'str'> -> 3
<class 'str'> -> 4
<class 'str'> -> 5
<class 'numpy.int64'> -> 1
<class 'numpy.int64'> -> 2
<class 'numpy.int64'> -> 3
<class 'numpy.int64'> -> 4
<class 'numpy.int64'> -> 5


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
    
(i) shape

(ii) size

In [21]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print(num_array)
print("shape is ",num_array.shape)
print("size is ",num_array.size)

[[1 2 3]
 [4 5 6]]
shape is  (2, 3)
size is  6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [31]:
a = np.zeros((3,3))
print(a)
print("size is ",a.size)
print("shape is ",a.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
size is  9
shape is  (3, 3)


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [30]:
a=np.eye(5)
print(a)
print("size is ",a.size)
print("shape is ",a.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
size is  25
shape is  (5, 5)
